export const LOG_IN_REQUEST = 'SESSION/LOG_IN_REQUEST'
export const LOG_IN_SUCCESS = 'SESSION/LOG_IN_SUCCESS'
export const LOG_IN_FAILURE = 'SESSION/LOG_IN_FAILURE'
export const LOG_IN_END_REQUEST = 'SESSION/LOG_IN_END_REQUEST'
export const HIDE_ALERT = 'SESSION/HIDE_ALERT'

export const LOG_OUT = 'SESSION/LOG_OUT'

export const PROFILE_GET_REQUEST = 'PROFILE/GET_REQUEST'
export const PROFILE_GET_SUCCESS = 'PROFILE/GET_SUCCESS'
export const PROFILE_GET_FAILURE = 'PROFILE/GET_FAILURE'
export const PROFILE_CLEAR = 'PROFILE/CLEAR'

export const NEWS_GET_REQUEST = 'NEWS/GET_REQUEST'
export const NEWS_GET_FAILURE = 'NEWS/GET_FAILURE'
export const NEWS_GET_SUCCESS = 'NEWS/GET_SUCCESS'
export const NEWS_CLEAR = 'NEWS/CLEAR'
